name=ESP32 WiFi Manager
version=1.0.0
author=Diazt Muhammad Firmansyah
maintainer=Diazt Muhammad Firmansyah
sentence=Single-header library to change ESP32 WiFi SSID & password from a phone via captive portal.
paragraph=No re-flash needed. ESP32 starts as a captive portal when no WiFi is configured. Configure WiFi credentials from any phone browser.
category=Communication
url=https://github.com/DiaztMF/ESP32-WiFi-Manager
architectures=esp32
includes=ESPWiFiManager.h
